import { z } from 'zod';

/**
 * Zod schema for validating UISchema generated by AI
 * Ensures the AI response conforms to the expected structure
 */
export const UISchemaSchema = z.object({
  component: z.string().min(1, 'Component name is required'),
  props: z.record(z.string(), z.any()),
  status: z.enum(['loading', 'success', 'error']).default('success'),
});

export type UISchemaZod = z.infer<typeof UISchemaSchema>;

/**
 * Validates a raw object against UISchema schema
 * Returns typed data or throws validation error
 */
export function validateUISchema(data: unknown): UISchemaZod {
  return UISchemaSchema.parse(data);
}
